#!/bin/bash

__fail() {
	echo -e "\nFAIL: $1\n"
	exit 2
}

__pass() {
	echo -e "\nPASS: $1\n"
}

pr() {
	cd $WORKDIR
	if [ -z "$2" ];then echo "Resetting to Dev ?";else echo "Preparing PR $2 ?";fi
	read aaa1
    #git reset --hard develop
	git fetch && git checkout -f develop
	git pull
	git branch | grep -v "develop" | xargs git branch -D 2>&1 | egrep -v "^error: branch"
	if [ ! -z "$2" ];then
		git checkout $2
		git pull
		git merge -m "Merge develop" develop
	fi
	grep -r "<<<< HEAD" && __fail "Address conflicts"
	__pass "No conflicts"
	if ( git status | sed 1,6d | egrep -v ".csv$|.svg$|^# *$|^nothing added to commit..*$" );then __fail "Found above files";fi
	__pass "No unexpected files"
	./vendor/bin/phinx migrate -e ${qasite}
	grunt dist
	clearc
	echo -e "\nAll done\n"
}

clearc() {
	(cd /tmp/templateCache/1/${qasite}.allbeauty.com && rm -rf * && echo -e "\n\nCached content $(ls -l)")
}

reindex() {
	d1="$(date)"
	echo -e "For complete reset, run;\nphp cron/generateProductAvailability.php\nphp cron/regenerateCatalogues.php\ncron/generateAlgoliaIndices.php force\n"
    clearc
	INDICES="$WORKDIR/storage/dd_Algolia*"
	cd $WORKDIR
	rm -rf $INDICES
	find $INDICES 2>/dev/null && __fail "$INDICES still remain"
    echo "Regenerating $(grep 'indexName' config.json) on https://www.algolia.com/apps/VS22L5JM4O/explorer/indices"
	php cron/generateAlgoliaIndices.php force
	echo -e "Started: $d1\nStopped: $(date)"
}

logs() {
	clear
	echo "Last ten logs updated..."
	ls -ltr /var/log/httpd/* | tail -10
	errlog="$(ls -tr /var/log/httpd/* | grep "error" | tail -1)"
	echo -e "\n<CR> to tail (or 'O' to open) $errlog ?";read OtO
	[[ "$OtO" =~ ^(O|o)$ ]] && vim $errlog || (echo "Tailing..." && tail -f $errlog)
}

# List files created or modified in last 60 mins
mod() {
     find . -cmin -60 -o -mmin -60
}
 
help() {
	echo -e "\nUsage: $0 [Option]\n\nOptions;"
	declare -F | grep -v "__" | sed -e "s/^declare -f /\t/g" 
	echo -e "\nWORKDIR: $WORKDIR\nSERVER.: $qasite\n"
}

[ -z "$WORKDIR" ] && __fail "WORKDIR not set"
qasite=$(uname -n | sed "s/\...*//g")
[ "$qasite" == "ip-10-90-0-249" ] && qasite="slaine"
[ "$qasite" == "ip-10-90-0-185" ] && qasite="hammerstein"

$1 $@
